animal_list = ['Iguana', 'Llama', 'Chinchillas', 'Dodo', 'Jellyfish', 'Rhinoceros', 'Hedgehog', 'Zebra', 'Possum', 'Wombat', 'Bison', 'Bull', 'Buffalo', 'Sheep', 'Meerkat', 'Mouse', 'Otter', 'Sloth', 'Owl', 'Vulture', 'Flamingo', 'Racoon', 'Mole', 'Duck', 'Swan', 'Lynx', 'Monitor lizard', 'Elk', 'Boar', 'Lemur', 'Mule', 'Baboon', 'Mammoth', 'Blue whale', 'Rat', 'Snake', 'Peacock', 'Panther', 'Leopard', 'Cheetah', 'Bear', 'Elephant', 'Polar bear', 'Turtle', 'Tortoise', 'Crocodile', 'Rabbit', 'Porcupine', 'Hare', 'Hen', 'Pigeon', 'Albatross', 'Crow', 'Fish', 'Dolphin', 'Frog', 'Whale', 'Alligator', 'Eagle', 'Flying squirrel', 'Ostrich', 'Fox', 'Goat', 'Jackal', 'Emu', 'Armadillo', 'Eel', 'Goose', 'Arctic fox', 'Wolf', 'Beagle', 'Gorilla', 'Chimpanzee', 'Monkey', 'Beaver', 'Orangutan', 'Antelope', 'Bat', 'Badger', 'Giraffe', 'Hermit Crab', 'Giant Panda', 'Hamster', 'Cobra', 'Hammerhead shark', 'Camel']
fruits_list=["apple","banana","cherry","kiwi","mango",
        "orange","papaya","pineapple","strawberry",
        "watermelon", "grape", "pear", "plum", "melon",
        "apricot", "blackberry", "blueberry", "cantaloupe",
        "coco", "cranberry", "grapefruit", "honeydew",
        "jackfruit", "kiwi", "lemon", "lime", "mandarin",
        "nectarine", "orange", "papaya", "peach"]
colors_list=[
    'red',
    'green',
    'blue',
    'yellow',
    'purple',
    'orange',
    'pink',
    'black',
    'white',
    'grey',
    'brown',
    'cyan',
    'magenta',
    'lime',
    'maroon',
    'olive',
    'teal',
    'navy',
    'silver',
    'gold',
    'aqua',
    'crimson',
    'chartreuse'
    ]
sports_list = [
    "Football (Soccer)",
    "Basketball",
    "Tennis",
    "Cricket",
    "Baseball",
    "Golf",
    "Rugby",
    "Hockey",
    "Boxing",
    "Martial Arts",
    "Swimming",
    "Athletics",
    "Table Tennis",
    "Badminton",
    "Volleyball",
    "Cycling",
    "Wrestling",
    "Skiing",
    "Snowboarding",
    "Surfing"
]
